/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tehfishey.pxmse;

import org.junit.Test;

import com.tehfishey.pxmse.MainApp;

import static org.junit.Assert.*;

public class MainAppTest {

	   @Test
	   public void testSayHello() {
	      MainApp app = new MainApp();
	      assertNotNull("Success", app.sayHello());
	   }
	}
