/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.tehfishey.spawnedit;

import org.junit.Test;

import com.github.tehfishey.spawnedit.Main;

import static org.junit.Assert.*;

public class MainTest {

	   @Test
	   public void testSayHello() {
	      Main app = new Main();
	     // assertNotNull("Success", app.sayHello());
	   }
	}
